[package]
name = "tack"
version = "0.1.0"
description = "a rusty scheme"
authors = ["agaric <agaric@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/blobject/tack"
repository = "https://github.com/blobject/tack"

[dependencies]
